# This workflow will do a clean install of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on:
  push:
    branches: [ master ]
     
jobs:
  cypress-test:
    runs-on: run on Chrome 88
    container: cypress/browsers:node14.17.0-chrome88-ff89  
    steps:
    - uses: actions/checkout@v2
    
    - name: Install cypress and verify 
    - run:
       npm ci
       $(npm bin)/cypress verify
       
    - name: Run Cypress tests
      run: npm run test:chrome
      continue-on-error: false
      
      
